### ISSUE TITLE
[Feat] Create page for each menus

### ISSUE THREAD

**Issue by seokzin** [seokzin/jandy#1]
## 설명(Description)

- 샘플을 수정하여 메뉴 틀을 갖춘다.

## ToDo

- [ ] 필요한 메뉴 추가
- [ ] 불필요한 메뉴 삭제
- [ ] 프로토타입에 맞게 메뉴 구성

## 주의사항 및 기타 comments

(PR관련 기타, comment 토의내용)
